Adding health check & promote to shared_deploy.yml

diff --git a/.github/workflows/shared_deploy.yml b/.github/workflows/shared_deploy.yml
--- a/.github/workflows/shared_deploy.yml
+++ b/.github/workflows/shared_deploy.yml
@@ -83,7 +83,7 @@ jobs:
       - name: Set up Cloud SDK
         uses: google-github-actions/setup-gcloud@v2
         with:
-          project_id: '${{ secrets.GCP_PROJECT }}'
+          project_id: '${{ secrets.PROJECT }}'
 
       - name: Prepare .npmrc
         run: |
@@ -113,12 +113,13 @@ jobs:
             --version ${{ steps.convert_tag.outputs.gcp_tag }} \
             ${{ inputs.DEPLOYMENT_CONFIG_FILENAME }}
 
-      - name: Validate /health version
+      - name: Validate health version
         id: health_check
         if: ${{ inputs.GCP_SERVICE_NAME }}
+        continue-on-error: true
         run: |
           EXPECTED_VERSION="${{ steps.validate_tag.outputs.tag }}-${{ inputs.ENVIRONMENT }}"
-          URL="https://${{ steps.convert_tag.outputs.gcp_tag }}-dot-${{ inputs.GCP_SERVICE_NAME }}-dot-${{ secrets.UAT_GCP_PROJECT }}.nw.r.appspot.com/health"
+          URL="https://${{ steps.convert_tag.outputs.gcp_tag }}-dot-${{ inputs.GCP_SERVICE_NAME }}-dot-${{ secrets.PROJECT }}.nw.r.appspot.com/health"
 
           echo "Checking $URL"
           echo "Expected version: $EXPECTED_VERSION"
@@ -139,14 +140,7 @@ jobs:
             sleep 3
           done
 
-          echo "::error ::Health validation failed", stopping version ${{ steps.convert_tag.outputs.gcp_tag }}"
-          gcloud app versions stop ${{ steps.convert_tag.outputs.gcp_tag }} \
-            --service=${{ inputs.GCP_SERVICE_NAME }} \
-            --project "${{ secrets.UAT_GCP_PROJECT }}" \
-            --quiet
-
-          # Fail the workflow explicitly
-          echo "Deployment failed because /health did not pass - version has been stopped"
+          echo "::error ::Health validation failed"
           exit 1
 
       - name: Promote traffic to new version
@@ -157,5 +151,18 @@ jobs:
           # Promote traffic entirely to the new version
           gcloud app services set-traffic ${{ inputs.GCP_SERVICE_NAME }} \
             --splits ${{ steps.convert_tag.outputs.gcp_tag }}=1 \
-            --project "${{ secrets.UAT_GCP_PROJECT }}" \
+            --project "${{ secrets.PROJECT }}" \
             --quiet
+
+      - name: Stop deployed version on health failure
+        if: ${{ inputs.GCP_SERVICE_NAME && steps.health_check.outcome != 'success' }}
+        run: |
+          echo "Health check failed, stopping version ${{ steps.convert_tag.outputs.gcp_tag }}"
+          gcloud app versions stop ${{ steps.convert_tag.outputs.gcp_tag }} \
+            --service=search-api \
+            --project "${{ secrets.PROJECT }}" \
+            --quiet
+
+          # Fail the workflow explicitly
+          echo "Deployment failed because /health did not pass - version has been stopped"
+          exit 1
